TVIP_APB_HOME	?= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/tvip-apb
export TVIP_APB_HOME

PROTOCOL	= apb
LANGURAGE	= systemverilog

FILE_LISTS	+= $(TVIP_APB_HOME)/compile.f
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/rtl/apb/block_0.sv
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/rtl/apb/block_1.sv
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/apb_env_pkg.sv
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/apb_top.sv
