TVIP_COMMON_HOME	?= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/tvip-common
export TVIP_COMMON_HOME

TVIP_AXI_HOME	?= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/tvip-axi
export TVIP_AXI_HOME

PROTOCOL	= axi4lite
LANGURAGE	= verilog

FILE_LISTS	+= $(TVIP_COMMON_HOME)/compile.f
FILE_LISTS	+= $(TVIP_AXI_HOME)/compile.f
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/rtl/axi4lite/block_0.v
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/rtl/axi4lite/block_1.v
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/axi4lite_env_pkg.sv
SOURCE_FILES	+= $(RGGEN_SAMPLE_TESTBENCH_ROOT)/env/axi4lite_top.sv
